sudo: required
services:
  - docker

before_install:
  - docker build -t denissrezan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true denissrezan/docker-react npm run test

language: generic

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-311578473255'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
