sudo: required
services:
  - docker

before_install:
  - docker build -t denissrezan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true denissrezan/docker-react npm run test

language: generic
